AUTOMAKE_OPTIONS = 1.4
ACLOCAL_AMFLAGS = -I config

bin_PROGRAMS = project_name

# BEGIN TEST SUITES
TEST_SUITES = 
# END TEST SUITES

check_PROGRAMS = ${TEST_SUITES}

EXTRA_DIST = BUGS INSTALL-unix $(m4sources)
